### ISSUE TITLE
Typo: VoJ

### ISSUE THREAD

**Issue by arrdem** [Malnorma/WMH_Vassal#12]
is "Vessel of Judgment"
should be "Vessel of Judgement"

**Comment by Malnorma** [comment]
I agree, but this is a consistently used spelling by Privateer:
https://privateerpress.com/warmachine/gallery/the-protectorate-of-menoth/battle-engines/vessel-of-judgment

From my dictionary:
usage: In British English the normal spelling in general contexts is judgement. However, the spelling judgment is conventional in legal contexts, and in North American English.

**Comment by arrdem** [comment]
Good lord. Okay. Noted.
