### ISSUE TITLE
Grymkin support

### ISSUE THREAD

**Issue by npe9** [Malnorma/WMH_Vassal#15]
Hey Malnorma, I was wondering if you were considering adding the Grymkin to the model. I'd be happy to add empty bases to the buildfiles and send you a pull request.

**Comment by Malnorma** [comment]
Good idea, but I was not keen to add Grymkin while they're still pre-release/possibly subject to changes (i.e. I'm not sure how much is guaranteed about them just yet).  But I did make an extension last night and posted it on Discord and the Lormahordes forum:
https://drive.google.com/open?id=0B1Lr55st8_qeOGhoS1FJTHAzLW8
This seemed a good compromise for now.

**Comment by npe9** [comment]
Would it be possible to put it in a branch? Then you'd just need to rebase it when things settled.

**Comment by Malnorma** [comment]
If code was involved, sure... unfortunately, the grody XML used by Vassal doesn't work that way.  If I branch it, and then try to do anything on the trunk (like add the models I still plan to add when I find out what they are), then ID numbers will clash when I try to bring the Grymkin into the trunk.  And not everything is referenced by ID number, so I can't even write a simple script to renumber them - some things use a string model path, potentially using different levels of escaping.  It's rather unappealing.

Given how small the extension is, I'm more tempted to remove all models from the main module and make each faction its own extension instead (and make a small utility to keep them all updated for the more novice users).  That way updates don't involve uploading/downloading 150+MB every time a few models are added.
