### ISSUE TITLE
Standardise control areas for the different base sizes.

### ISSUE THREAD

**Issue by Malnorma** [Malnorma/WMH_Vassal#3]
For example, Lylyth3 and Xerxis2 have the same size base and control area, but Xerxis' is larger by a few pixels.  Having a reference table of values to use for each base size would be useful.

**Comment by fatzech** [comment]
Unless you want to do all that work a few pixels isn't going to kill anyone ;)

**Comment by Malnorma** [comment]
Yeah, there's no way I'm doing it by hand... but adjusting the cleaning script to standardise things is something I always approve of :D

**Comment by Malnorma** [comment]
Actually, I tried something out today - it's possible to have the ctrl area calculated based on properties.  Changing it will be a bigger task, but worth it in the end if you only have to remember to set a Focus value on the caster instead of a control area in pixels.  I'll take this on once we get the repo in sync with your latest work.

**Comment by Malnorma** [comment]
One limitation of doing it this way is that the ctrl area is then a single colour for all models - this could be worked around by doing a per-faction prototype instead, but I'm not sure anyone particularly cares about the colour of their control area shading...  I could be wrong though.

**Comment by fatzech** [comment]
The other consideration we also need to look at is sqire and corollary and
how it would affect it.

**Comment by Malnorma** [comment]
Those are done with additional Area of Effect traits which would be unaffected, but they could also be improved by toggling a 'corollary bonus' or 'squire bonus' (faction-specific toggles that just increase a second variable.  Then the ctrl-area radius becomes something like BaseRadius + 60 * (Focus + CtrlBonus), and the toggle flips CtrlBonus between 0 and 1.
